branches:
  - main

ci: false

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalCommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: patch
        - type: docs
          release: patch
        - type: style
          release: false
        - type: test
          release: false
        - type: build
          release: false
        - type: ci
          release: false
        - type: chore
          release: false
        - type: chore
          scope: deps
          release: patch
  - '@semantic-release/git'

preset: conventionalcommits
